name: Pull Request on Branch Push

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      # ToDo: use devcontainers/ci@v0.3 to reuse the devcontainer
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run build
